apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: wallet-web-ui-hpa
spec:
  maxReplicas: 30
  minReplicas: 5
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: wallet-web-ui-deployment
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
