#!/usr/bin/python3

import sys
import os
import http.client
import json
import hashlib

args = sys.argv[1:]
# @todo: support mainnet
DAPP_URL = "https://sdk-toolkit-dev.blocto.app"
DEV_DAPP_ID = "5d35c67e-7f37-4e4c-81ba-e7fafc92fd0a"

# @todo: support mainnet contract addresses
EVM_ADDRESSES = {
  'ethereum': '0xe4500382e9e060925Eb9f60Ede902E9098F426d7',
  'bsc': '0x3CC26344Aa3f2d12005f68CAc01EDaf0840e98F3',
  'polygon': '0xDC5Fd9220511A7211719dD8206Ec2D686054bCC0',
  'avalanche': '0xDC5Fd9220511A7211719dD8206Ec2D686054bCC0',
}
EVM_CHAINS = ['ethereum', 'polygon', 'tron', 'bsc', 'avalanche'] 

CODE_ERROR="""
  auth code not found

  to set the auth code, run:
    export WALLET_DEV_CODE="your auth code"
"""
HELP_MESSAGE = """
  transaction

    EVM
    
      dev-tool [blockchain] transfer [address] [value]
      dev-tool [blockchain] setValue [value]
    
    Aptos

      dev-tool aptos script transfer [address] [value]
      dev-tool aptos function transfer [address] [value]

  sign message

    dev-tool [evm-chains] sign [message] ([method])
    dev-tool aptos sign [message]

  help

    dev-tool help
"""

def init_connection():
  try:
    server = os.environ['WALLET_DEV_SERVER'] 
  except:
    server = "wallet-v2.blocto.app"
  connection = http.client.HTTPConnection(server) if server.startswith("localhost") else http.client.HTTPSConnection(server)
  return connection

def get_code():
  code = os.environ['WALLET_DEV_CODE']
  if code == "":
    print(CODE_ERROR)
    code = None
  return code

def get_dev_url():
  try:
    server = os.environ['WALLET_DEV_URL'] 
  except:
    server = "http://localhost:3000"
  return server

def format_evm_params(params, types):
  data = ""
  for i in range(0, len(params)):
    if str(types[i]).startswith("uint"):
      data += hex(int(params[i]))[2:].zfill(32)
  return data

def make_evm_payload(blockchain, account):
  transaction = {}
  transaction['from'] = account
  transaction['maxFeePerGas'] = "0x9502f90e"
  transaction['maxPriorityFeePerGas'] = "0x9502F900"
  transaction['value'] = hex(int(args[3])) if len(args) > 3 else "0"

  method = args[1] if len(args) > 1 else ""

  if method == "transfer":
    transaction['to'] = args[2]
  if method == "setValue":
    signature = "0x55241077"
    value = hex(int(args[2]))[2:].zfill(64)
    transaction['data'] = "{signature}{value}".format(signature=signature, value=value)
    transaction['to'] = EVM_ADDRESSES[blockchain]
  return [transaction]

def make_aptos_payload():
  payload = {}
  if args[1] == 'function' and args[2] == 'transfer':
    payload['arguments'] = [args[3], args[4]]
    payload['function'] = "0x1::coin::transfer"
    payload['type'] = "entry_function_payload"
    payload['type_arguments'] = ['0x1::aptos_coin::AptosCoin']
  elif args[1] == 'script' and args[2] == 'transfer':
    payload['arguments'] = [args[3], args[4]]
    payload['code'] = {
      "bytecode": "0xa11ceb0b0500000005010002030205050706070d170824200000000100010003060c0503000d6170746f735f6163636f756e74087472616e736665720000000000000000000000000000000000000000000000000000000000000001000001050b000b010b02110002",
      "abi": {
        "name": "main",
        "visibility": "public",
        "is_entry": True,
        "generic_type_params": [],
        "params": [
          "&signer",
          "address",
          "u64"
        ],
        "return": []
      }
    }
    payload['type'] = "script_payload"
    payload['type_arguments'] = []
  return payload

def __main__():

  if len(args) > 1:
    blockchain = args[0]
    op = args[1]
  else:
    op = args[0]

  if op == "sign":
    code = get_code() 
    if code is None: return
    dev_url = get_dev_url()

    try:
      connection = init_connection()
      url = "/api/{blockchain}/user-signature".format(blockchain=blockchain)

      payload = {}

      # @todo: support flow sign
      if blockchain in EVM_CHAINS:
        payload['message'] = args[2]
        payload['method'] = args[3] if len(args) > 3 else "eth_sign"
      elif blockchain == 'aptos':
        payload['message'] = args[2]
        payload['nonce'] = "dev-tool-sign"
        payload['address'] = True
        payload['application'] = True
        payload['chainId'] = True
      
      request_body = json.dumps(payload)

      connection.request('POST', url, request_body, {
        'Content-type': 'application/json',
        'Blocto-Session-Identifier': code
      })
      response = json.load(connection.getresponse())
      signature_id = response['signatureId']
      generated_url = "{dev_url}/{dapp_id}/{blockchain}/user-signature/{signature_id}".format(dev_url=dev_url, dapp_id=DEV_DAPP_ID, blockchain=blockchain, signature_id=signature_id)
      os.system('open "{url}"'.format(url = generated_url))

    except IndexError:
      print("\nError: arguments format")
      print(HELP_MESSAGE)
    except Exception as e:
      print("Error: {}".format(e))

  elif op == "help":
    print(HELP_MESSAGE)
  else:
    # handle transaction
    code = get_code() 
    if code is None: return
    dev_url = get_dev_url()

    try:
      connection = init_connection()
      accounts_url = "/api/{blockchain}/accounts".format(blockchain=blockchain)

      connection.request('GET', accounts_url, None, {
        'Content-type': 'application/json',
        'Blocto-Session-Identifier': code
      })
      response = json.load(connection.getresponse())
      account = response['accounts'][0]

      payload = None

      # @todo: handle solana/flow tx
      if blockchain in EVM_CHAINS:
        payload = make_evm_payload(blockchain, account)
      elif blockchain == 'aptos':
        payload = make_aptos_payload()
      request_body = json.dumps(payload)

      url = "/api/{blockchain}/authz".format(blockchain=blockchain)
      connection.request('POST', url, request_body, {
        'Content-type': 'application/json',
        'Blocto-Session-Identifier': code
      })
      
      response = json.load(connection.getresponse())
      auth_id = response['authorizationId']
      generated_url = "{dev_url}/{dapp_id}/{blockchain}/authz/{auth_id}".format(dev_url=dev_url, dapp_id=DEV_DAPP_ID, blockchain=blockchain, auth_id=auth_id)
      os.system('open "{url}"'.format(url = generated_url))

    except IndexError:
      print("\nError: arguments format")
      print(HELP_MESSAGE)
    except Exception as e:
      print("Error: {}".format(e))

__main__()